name: Deploy to GitHub Pages

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install npm dependencies
      run: npm install
      
    - name: Build Tailwind CSS
      run: npm run css:prod
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build and publish
      run: dotnet publish -c Release -o dist
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/wwwroot
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4